[build]
  command = "npm run build"
  publish = "out"
  environment = { NEXT_PUBLIC_SITE_URL = "https://ushom.netlify.app", NEXT_PUBLIC_MATOMO_URL = "https://advise.matomo.cloud/", NEXT_PUBLIC_MATOMO_SITE_ID = "3" }
[[plugins]]
  package = "@netlify/plugin-nextjs"
