---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/pages
  label: Pages
  create: documents
  match: "**/*"
  templates:
  - page
- type: heading
  label: Pages spéciales
- type: document
  path: content/home.json
  label: Accueil
- type: document
  path: content/about.json
  label: Qui Sommes-Nous
- type: heading
  label: Autre
- type: document
  path: content/datas/landlords.json
  label: Territoires
- type: document
  path: content/datas/organizational.json
  label: Organigramme
- type: document
  path: content/datas/interlocutors.json
  label: Interlocuteurs
- type: document
  path: content/nav/main.json
  label: Menu principal
- type: document
  path: content/main.json
  label: Paramètres
upload_dir: public/static/uploads
public_path: "/static/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - NEXT_PUBLIC_SITE_URL=https://ushom.netlify.app
  preview_output_directory: out
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run dev
